controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mercure_jwt:
    path: /api/mercure-jwt
    controller: App\Controller\ChatController::getMercureJwt
